### ISSUE TITLE
Breaks server commands

### ISSUE THREAD

**Issue by zedwick** [umollu/ash#4]
With Ash 1.1.2 installed client-side, no commands provided by the server work. Vanilla commands (/list) do work, however.

**Comment by stw222** [comment]
ive had kind of the same problem.
most server commands work but there are a few that show up red (even thought they work on the server) when anyone types them on the server (modded or not) and when i use those commands while using mods it will say that its not a valid command. i uninstalled all of my mods and re installed them one at a time and narrowed it down to this mod being the cause.

**Comment by SnoFox** [comment]
I can also confirm this. Using ASH 1.1.2 on Minecraft 1.14.4, some Bukkit plugin commands fail to work. For example, `/lp listgroups` from LuckPerms returns an "Unknown command at position ..." error, even though the server is auto-completing it.

Interestingly, `/lp` and `/lp help` work, though other subcommands do not.
